### ISSUE TITLE
Rails 5 

### ISSUE THREAD

**Issue by zsan** [pmviva/mention_system#1]
Hi,

I think its time to support for rails 5 :)

**Comment by pmviva** [comment]
I haven't spent much time on this gem lately but I plan to support rails 5 when I have some time to hack.

**Comment by zsan** [comment]
Thanks,

I thought it just about to remove deps set in `mention_system.gemspec` lol

**Comment by pmviva** [comment]
Yeah it is, but also testing that the gem is not using depprecated or removed apis.

**Comment by clairity** [comment]
@pmviva i was just about to try out mention_system on a rails 5 project, so this would be very helpful. :)

**Comment by pmviva** [comment]
@clairity I've pushed to rubygems a new version that adds support for rails 5.

I updated the appraisal dependencies to test the gem against the latest rails releases of 4.1, 4.2 and 5.0 additionaly i fixed a warning in spec. I need to remove a deprecation warning in the Migration itself as recommended in rails 5.0 but breaks in 4.1+

Try it out and let me know.
