### ISSUE TITLE
Is it possible to use @ and # prefix

### ISSUE THREAD

**Issue by newterminator** [pmviva/mention_system#2]
Hi @pmviva , 
First of all, I wanted to thank you for extending/improving on _cmer/socialization_ mention implementation. 

I wanted to ask that is it possible to use @ prefix for as in your example scenario of a post mentioning a user, and then having also the # prefix work for mentioning the tags in a comment. (Specifically I wanted to make it work with acts-as-taggable-on)

Any advice on how would I go about implementing it will be helpful.

**Comment by pmviva** [comment]
I would suggest using two different mention processors, for example having a UserMentionProcessor and HashtagMentionProcessor

Each of one redefines the mention_prefix method the first one using @ and the second one using # 

The use case would be:

// user_mention_processor.rb
class UserMentionProcessor < MentionSystem::MentionProcessor
  private:
  def mention_prefix
    "@"
  end
end
// hashtag_mention_processor.rb
class HashtagMentionProcessor < MentionSystem::MentionProcessor
  private:
  def mention_prefix
    "#"
  end
end

Then in controller or any service object you would do something like:

userProcessor = UserMentionProcessor.new
hashtagProcessor = HashtagMentionProcessor.new

userProcessor.process_mentions(post)
hashtagProcessor.process_mentions(post)

If this, for some reason, doesn't meet your needs, please clarify the use case a little bit and I'll look into it.

**Comment by newterminator** [comment]
@pmviva ,
Thanks for responding to my query. Okay your comment helped me understand differentiating the two prefixes, and having a separate mention processor for each of the prefixes. I am gonna implement your solution, and most likely I think its gonna work for my case. 

I will close the issue, and report back if it worked or not.

**Comment by newterminator** [comment]
@pmviva , Just wanted to 'mention' - lol - that your described solution worked. Thanks again for your gem.
