### ISSUE TITLE
Support for rails 6

### ISSUE THREAD

**Issue by apuntovanini** [pmviva/mention_system#4]
Any plans to support rails 6? Would you accept PR for this?
Thanks

**Comment by pmviva** [comment]
No plans right now, I havent developed in rails since a year. I would
accept a PR but im on hollidays right now, so if you like fork the repo and
make a PR and I will merge it when I come back.

Regards
Pablo

**Comment by apuntovanini** [comment]
Done! Thanks for the quick response, sent a PR that should fix the issue, enjoy your holidays!

**Comment by pmviva** [comment]
I've implemented support for rails 6. Couldn't merge your pull request tough, but thanks a lot anyway!
